export enum Students {
    id = 'Уникальный номер',
    average_rating = 'Средний рейтинг',
    email = 'Электронная почта',
    fathers_name = 'Отчество',
    first_name = 'Имя',
    last_name = 'Фамилия',
    group = 'Группа',
    number = 'Номер',
    update_date = 'Дата обновления',
    mark = 'Оценка',
    student = 'Студент',
    teacher = 'Преподаватель',
    subject = "Предмет",
    subject_block = "Предметный блок",
    term = "Семестр",
    control_type = "Тип контроля",
    datetime = "Дата сдачи",
    retake_count = "Номер пересдачи",
    is_final = "Закрыта"
}